config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  devise_for :users
  root 'welcome#index'
  get 'my_portfolio', to: "users#my_portfolio"
  get 'search_stock', to: "stocks#search"
  get 'friend_feed', to: "users#friend_feed"
  get 'search_friend', to: "users#search_friend"
  resources :followings, only: [:create, :destroy]
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :user
  belongs_to :followee, class_name: 'User' 
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true
  def self.stock_lookup(ticker_symbol)
    client = IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
      endpoint: 'https://sandbox.iexapis.com/v1'
    )
    begin
      new(ticker: ticker_symbol.upcase , name: client.company(ticker_symbol).company_name , last_price: client.price(ticker_symbol) )
    rescue => exception
      return nil
    end
  end

  def self.check_db(ticker_symbol)
    find_by(ticker: ticker_symbol)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :followings
  has_many :followees, through: :followings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def count_under_limit?
    stocks.count < 10
  end

  def already_tracking?(ticker_symbol)
    stock = Stock.check_db(ticker_symbol)
    return false if stock.nil?
    
    !stocks.find_by(ticker: ticker_symbol).nil?
  end
  def can_track_stock?(ticker_symbol)
    count_under_limit? && !already_tracking?(ticker_symbol)
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous"
  end

  
  def self.matches(column_name, matching_pattern)
    where("#{column_name} like ?", "%#{matching_pattern}%")
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.search(param)
    search_results = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless search_results
    search_results
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def not_friends_with?(friend_id)
    !self.followees.where(id: friend_id).exists?
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/followings_controller.rb
class FollowingsController < ApplicationController
  def create
    new_following = Following.new(user_id: current_user.id, followee_id: params[:friend])
    new_following.save

    flash[:notice] = "Started following #{User.find(params[:friend]).full_name}"
    redirect_to friend_feed_path

  end

  def destroy
    to_be_unfollowed = Following.find_by(user_id: current_user.id, followee_id: params[:id])
    to_be_unfollowed.destroy
    flash[:notice] = "Stopped following #{User.find(params[:id]).full_name}"
    redirect_to friend_feed_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    if params[:stock].present?
      @stock = Stock.stock_lookup(params[:stock])
      if @stock
        respond_to do |format|
          format.js { render partial: 'users/result' }
        end
          
      else
        respond_to do |format|
          flash.now[:alert] = "Please enter a valid symbol to search"
          format.js { render partial: 'users/result' }
        end
                
      end

      
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a symbol to search"
        format.js { render partial: 'users/result' }
      end
      
      
    end
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock = Stock.check_db(params[:ticker])
    if stock.nil?
      stock = Stock.stock_lookup(params[:ticker])
      stock.save
    end
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:notice] = "Stock #{stock.name} was successfully added to your portfolio."
    redirect_to my_portfolio_path
  end

  def destroy
    stock_id = params[:id]
    user_stock = UserStock.find_by(user_id: current_user.id, stock_id: stock_id)
    user_stock.destroy
    flash[:notice] = "#{Stock.find(stock_id).ticker} was successfully removed from your portfolio"
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @tracked_stocks = current_user.stocks
    @user = current_user
  end
  def friend_feed
    @followee_list = current_user.followees
  end

  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end

  def search_friend
    if params[:friend].present?
      @friend_list = User.search(params[:friend])
      @friend_list = current_user.except_current_user(@friend_list)
      if !@friend_list.empty?
        respond_to do |format|
          format.js { render partial: 'users/friend_result' }
        end
          
      else
        respond_to do |format|
          flash.now[:alert] = "No results found for given query"
          format.js { render partial: 'users/friend_result' }
        end
                
      end

      
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a name or an email to search"
        format.js { render partial: 'users/friend_result' }
      end
      
      
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def index

    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followings_helper.rb
module FollowingsHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/followees/_list.html.erb
<div class="card card-header stock-info">
  <table>
    <tbody>
      <% @friend_list.each do |friend| %>
        <tr>
          <td><strong>Name: </strong> <%= friend.full_name %></td>
          <td><strong>email: </strong> <%= friend.email %></td>
          <td><strong>Actions </strong> <%= link_to 'View Profile', user_path(friend), class: "btn btn-success btn-sm ml-4" %>
          <% if current_user.not_friends_with?(friend.id) %>
            <%= link_to 'Add friend?', followings_path(friend: friend), class: "btn btn-success btn-sm ml-4", method: :post %>
          <% else %>
            <span class="badge badge-secondary"> You are already friends </span>
          <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/_messages.html.erb
<% if notice %>
	<div class='alert alert-success'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
	<div class='alert alert-danger'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= alert %>
	</div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container">
        <%= link_to 'FinanceTracker', root_path, class: "navbar-brand"%>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <% if current_user %>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item <%= 'active' if request.path == my_portfolio_path %>">
                <%= link_to 'Portfolio', my_portfolio_path, class: "nav-link"%>
              </li>
              <li class="nav-item <%= 'active' if request.path == friend_feed_path %>">
                <%= link_to 'Friend feed', friend_feed_path, class: "nav-link"%>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Profile
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
                    <%= fa_icon 'edit'%> <%= 'Edit profile' %>
                  <% end %>
                  <a class="dropdown-item" href="#">Another action</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="#">Something else here</a>
                </div>
              </li>
            
            </ul>
            <ul class="navbar-nav ml-auto">
              <li class="mt-2 mr-3">
                <%= fa_icon 'user' %> <%= current_user.full_name %>
              </li>
              <li class="nav-item">
                <%= link_to 'Logout', destroy_user_session_path, class: "btn btn-danger mr-2", method: :delete %>
              </li>
            </ul>
            
          </div>
        <% end  %>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= render 'layouts/messages'%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_list.html.erb
<div class="row">
  <div class="col-9">
  
    <table class="table table-bordered table-striped table-dark table-hover">
      <thead>
        <tr>
          <th scope="col">Ticker</th>
          <th scope="col">Name</th>
          <th scope="col">Price</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
      <% @tracked_stocks.each do |stock| %>
        <tr>
          <td><%= stock.ticker %></td>
          <td><%= stock.name %></td>
          <td><%= stock.last_price %></td>
          <td>
            <% if current_user.can_track_stock?(stock.ticker) %>
                  <%= link_to 'Add to porfolio', user_stocks_path(user: current_user, ticker: stock.ticker), class: "btn btn-success ml-4", method: :post %>
                <% elsif current_user.id != @user.id %>
                  <span class="badge badge-secondary">You are already tracking
                  <% if current_user.already_tracking?(stock.ticker) %>
                      this stock</span>
                  <% else %>
                      10 stocks</span>
                    <% end %>
                <% end %>
            <% if current_user.id == @user.id %>
            <%= link_to 'Remove', user_stock_path(stock), class: 'btn btn-sm btn-warning', data: { confirm: "Are you sure?" }, method: :delete %>
          </td>
          <% end %>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/_friend_result.html.erb
<div class="stock-info">
  <%= render 'layouts/messages'%>
</div>

<% if !@friend_list.empty? %>
  <%= render 'followees/list' %>
<% end %>

app/views/users/_friend_result.js.erb
document.querySelector('#response').innerHTML = '<%= escape_javascript(render 'users/friend_result.html') %>'

app/views/users/_result.html.erb
<div class="stock-info">
  <%= render 'layouts/messages'%>
</div>

<% if @stock %>
  <div class="card card-header stock-info">
    <strong>Ticker: </strong> <%= @stock.ticker %>
    <strong>Name: </strong> <%= @stock.name %>
    <strong>Price: </strong> <%= @stock.last_price %>
    <% if current_user.can_track_stock?(@stock.ticker) %>
      <%= link_to 'Add to porfolio', user_stocks_path(user: current_user, ticker: @stock.ticker), class: "btn btn-success ml-4", method: :post %>
    <% else %>
      <span class="badge badge-secondary">You are already tracking
      <% if current_user.already_tracking?(@stock.ticker) %>
        this stock</span>
      <% else %>
        10 stocks</span>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/users/_result.js.erb
document.querySelector('#response').innerHTML = '<%= escape_javascript(render 'users/result.html') %>'

app/views/users/friend_feed.html.erb
<h1> Welcome to the friend feed </h1>
<div class="search-area">
  <h3>Search friends</h3>
  <%= form_tag search_friend_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 some-right-padding">
        <%= text_field_tag :friend, params[:friend], placeholder: "Search with name or email", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-left-padding">
      <%= button_tag type: :submit, class: "btn btn-success btn-lg" do %>
        <%= fa_icon 'search'%>
      <% end %>
      </div>
    </div>
  <% end %>
</div>
<div id="response">

</div>
<% if !@followee_list.empty? %>  
  <div class="row">
    <div class="col-9">
      <table class="table table-bordered table-striped table-hover">
        <thead>
          <tr>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
        <% @followee_list.each do |followee|%>
          <tr>
            <td><%= followee.full_name %></td>
            <td><%= followee.email %></td>
            <td>
              <%= link_to 'Stop following', following_path(followee), data: { confirm: "Are you sure" }, class: "btn btn-sm btn-warning", method: :delete %>
              <%= link_to 'View Profile', user_path(followee), class: "btn btn-success btn-sm ml-4" %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>


<% else %>
  <h3> It's lonely here, follow somebody to add them into friends feed! </h3>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>
<div class="search-area">
  <h3>Search stocks</h3>
  <%= form_tag search_stock_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-sm-9 some-right-padding">
        <%= text_field_tag :stock, params[:stock], placeholder: "Search with stock ticker", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-sm-3 no-left-padding">
      <%= button_tag type: :submit, class: "btn btn-success btn-lg" do %>
        <%= fa_icon 'search'%>
      <% end %>
      </div>
    </div>
  <% end %>
</div>

<div id="response">

</div>

<% if !@tracked_stocks.empty? %>
  <%= render 'stocks/list' %>
<% end %>

app/views/users/show.html.erb
<h1><%=  "Welcome to #{@user.full_name}'s page" %></h1>


<div class="card card-header stock-info">
  <table class="col-md-12">
    <tbody>
      <tr>
        <td><strong>Name: </strong> <%= @user.full_name %></td>
        <td><strong>email: </strong> <%= @user.email %></td>
        <td><% if current_user.not_friends_with?(@user.id) %>
          <%= link_to 'Add friend?', followings_path(friend: @user), class: "btn btn-success btn-sm ml-4", method: :post %>
        <% else %>
          <span class="badge badge-secondary"> You are already friends </span>
        <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div>
<% if !@tracked_stocks.empty? %>
  <%= render 'stocks/list' %>
<% else %>
  <p class='lead'> This user is not tracking any stocks </p>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome to finance tracker!</h1>

<h3> Go to stock tracker or friends feed for tracking your portfolio and friends!</h3>